spring:
  application:
    name:
      trainee-app-with-data-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/ust_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port:
    8000
