spring:
  application:
    name:
      trainee-app-with-data-jpa
  datasource:
    url: jdbc:mysql://localhost:3306/ust_db
    username: root
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port:
    8000
