apiVersion: apps/v1 
kind: Deployment  
metadata: 
   name: easy-recipes-deployment

spec:  
  selector:
    matchLabels:
      app: easy-recipes


  replicas: 1 
  template:
    metadata:
      labels:
        app: easy-recipes
    spec:   

      containers:
      - name: easy-recipes
        image: 'ram1uj/easy-recipes' 
        ports:
        - containerPort: 80 