apiVersion: v1
kind: Service 
metadata: 
  name: easy-recipes
spec: 
  selector:
    app: easy-recipes
  ports:
    - port: 80  
      targetPort: 80
      nodePort: 30020 
      name: http
  type: NodePort