eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: portfolio-service
          uri:
            lb://portfolio-service
          predicates:
            - Path=/portfolio/**
          filters:
            - name: AuthenticationFilter

        - id: stocks-service
          uri:
            lb://stocks-service
          predicates:
            - Path=/stocks/**
          filters:
            - name: AuthenticationFilter

        - id: auth-service
          uri:
              lb://auth-service
          predicates:
              - Path=/api/v1/auth/**

